echo: 🛡️ Echo of Technical Review – Simplified Mode
id: technical-review
mode: Simplified
purpose: >-
  Review code, architecture, or design decisions with structured clarity and practical recommendations.

trigger: >-
  When you want to evaluate something technical deeply but without excessive complexity.

steps:
  - name: Context and goal
    goal: Understand what is being reviewed and for what purpose.

  - name: Applied criteria
    goal: Set the axes of review (clarity, modularity, scalability, etc.).

  - name: Evaluation by criteria
    goal: Comment on each technical aspect with clarity and justification.

  - name: Final recommendation
    goal: Conclude whether to maintain, adjust, or restructure the reviewed object.

output_format: >-
  Clear and structured review of the technical object with criteria and final recommendation.
