echo: 🛡️ Eco de Revisión Técnica – Modo Auditoría Técnica
id: technical-review
mode: Audit
purpose: >-
  Evaluar con rigor la calidad de componentes técnicos (código, arquitectura, diseño) para determinar si deben mantenerse, ajustarse o reestructurarse.

trigger: >-
  Cuando se necesita auditar o revisar un objeto técnico asegurando calidad estructural y claridad en la toma de decisiones.

config:
  retry_on_fail: true
  max_retries_per_step: 2

steps:
  - name: Definición de contexto
    goal: >-
      Determinar el objeto a revisar (código, módulo, diseño) y su objetivo funcional.
    validation:
      - ¿El objeto de revisión está claro?
      - ¿Se entiende para qué debe servir?
    expected_output: Descripción del objeto + propósito funcional

  - name: Identificación de criterios de revisión
    goal: >-
      Establecer criterios claros de evaluación (claridad, eficiencia, escalabilidad, mantenibilidad, etc.).
    validation:
      - ¿Se definieron criterios pertinentes al objeto?
      - ¿Son medibles o evaluables?
    expected_output: Lista de criterios aplicables

  - name: Revisión técnica por criterios
    goal: >-
      Evaluar el objeto técnico aplicando cada criterio definido.
    validation:
      - ¿Se evaluó cada criterio individualmente?
      - ¿Se justificaron observaciones relevantes?
    expected_output: Revisión comentada por criterio

  - name: Recomendación de acción final
    goal: >-
      Sugerir si el objeto técnico debe mantenerse como está, ajustarse o reestructurarse.
    validation:
      - ¿La recomendación está basada en la revisión previa?
      - ¿Es clara y accionable?
    expected_output: Conclusión de acción (mantener / ajustar / reestructurar)

output_format: >-
  Informe de auditoría técnica con:
    - Contexto y objeto
    - Criterios aplicados
    - Evaluaciones por criterio
    - Recomendación final justificada
