echo: 🛡️ Eco de Revisión Técnica – Modo Simplificado
id: technical-review
mode: Simplified
purpose: >-
  Revisar técnicamente código, arquitectura o decisiones de diseño con claridad estructurada y recomendaciones prácticas.

trigger: >-
  Cuando se quiere evaluar algo técnico con profundidad pero sin complejidad excesiva.

steps:
  - name: Contexto y objetivo
    goal: Saber qué se está revisando y para qué.

  - name: Criterios aplicados
    goal: Establecer los ejes de revisión (claridad, modularidad, escalabilidad, etc.).

  - name: Evaluación por criterio
    goal: Comentar cada aspecto técnico con claridad y justificación.

  - name: Recomendación final
    goal: Concluir si mantener, ajustar o reestructurar el objeto revisado.

output_format: >-
  Revisión clara y estructurada del objeto técnico con criterio y recomendación.
